#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/2148089P ensure=absent force=true
puppet resource file /tmp/2148089P ensure=directory
puppet resource file /tmp/2148089P/work ensure=absent force=true
puppet resource file /tmp/2148089P/work ensure=directory
cd /tmp/2148089P/work
git clone https://github.com/rp-sddo-23003337/POC_REPO.git
cp -p /tmp/2148089P/work/POC_REPO/2148089P_index.html /tmp/2148089P/work/POC_REPO/index.html
cp -p /tmp/2148089P/work/POC_REPO/index.html /var/www/html
